# Configuration settings for ZED-F9P device, see https://github.com/KumarRobotics/ublox
# for avaliable configurations

debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyACM50        # Path to device port
frame_id: gps               # ROS name prepended to frames produced by node
rate: 1                     # in Hz
nav_rate: 1                 # in Hz :For HPG Ref devices, nav_rate should be exactly 1Hz

#dynamic_model: sea
                     # Max Alt: 500m
                     # Max Horizontal Velocity: 25 m/s,
                     # Max Vertical Velocity: 5 m/s
#uart1:
#  baudrate: 115200
#  in: 16                     # RTCM 3
#  out: 0                    # No UART out for rover

# TMODE3 Config
tmode3: 0                   # Disabled
sv_in:
  reset: false              # True: disables and re-enables survey-in (resets)
                             # False: Disables survey-in only if TMODE3 is

  min_dur: 60               # Survey-In Minimum Duration [s]
  acc_lim: 1                # Survey-In Accuracy Limit [m]

arp:
  position_hp: True

# Which satelites are contacted
gnss:
  galileo: true
  gps: true
  glonass: true
  beidou: true
  qzss: true

dgnss_mode: 3

# Messages to be published
#publish:
#  all: true

publish:
  #all: True
  nav:
    poshllh: True
    heading: True
